services:
  xiaomusic:
    image: hanxi/xiaomusic
    container_name: xiaomusic
    restart: unless-stopped
    ports:
      - 58090:8090
    environment:
      XIAOMUSIC_PUBLIC_PORT: 58090
    volumes:
      - /vol2/1000/sata-1T/docker/ xiaomusic/app/music:/app/music  #下载的歌曲会再这里
      - /vol2/1000/sata-1T/docker/ xiaomusic/app/conf:/app/conf
      - /vol2/1000/sata-1T/music:/app/music/music1   #NAS本地的音乐地址
